# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/c_accum_0/c_accum_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_accum_0 || ORIG_REF_NAME==c_accum_0} -quiet] -quiet
